version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://jonathan:1234@clustermindy.5b4dixw.mongodb.net/?retryWrites=true&w=majority&appName=ClusterMindy
      - JWT_SECRET=miclaveultrasecreta

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
