services:
  - type: web
    name: mindy-frontend
    env: docker
    plan: free
    dockerContext: ./frontend
    dockerfilePath: Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://mindy-backend.onrender.com

  - type: web
    name: mindy-backend
    env: docker
    plan: free
    dockerContext: ./backend
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: tu-uri
      - key: JWT_SECRET
        value: tu-clave
