services:
  - type: web
    name: mindy-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: .
    plan: free

  - type: web
    name: mindy-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    plan: free
